Repository meilisearch/charabia, pull requests merged in 2022-09, with the labels that each got.

#121 Minor fixes in the just added update-version CI
  .github/workflows/update-cargo-toml-version.yml
Labels: skip changelog

#125 Upgrade ubuntu-18.04 to 20.04
  .github/workflows/publish.yml
  .github/workflows/rust.yml
Labels: maintenance

#127 Update Japanese performances after #126
  README.md
Labels: documentation, skip changelog
